### ISSUE TITLE
Path argument must be a string not undefined

### ISSUE THREAD

**Issue by ghostdevv** [roxiness/configent#1]
The issue:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
```

I tested this on Windows and Linux (via WSL), I used node 14.x, 12.x, and 10.x and only happens on 10.x across both Linux and Windows.

The issue is with the last function trying to run `module['parent'].path` which is undefined on node 10.x

Configent.js
```js
function getParentModuleDir(path = module['parent'].path) {
    // walk through parents till we find a package.json
    return (existsSync(resolve(path, 'package.json')))
        ? path
        : getParentModuleDir(dirname(path))
}
```

**Comment by jakobrosenberg** [comment]
Would adding a Node 12 requirement fix this?

**Comment by ghostdevv** [comment]
It's just a issue with `module['parent'].path` not existing on some node versions so any alternative that works across the versions needed would be great @jakobrosenberg
